### PR TITLE
hariom check kr file

### PR DESCRIPTION
**Pull request by Raizel-thebloodstorm**

### CODE REVIEW

**Comment by hariomhearts** [comment]
comment proper likha kr warna submit nhi karung

**Comment by Raizel-thebloodstorm** [comment]
> comment proper likha kr warna submit nhi karung

chal be gandu

**Comment by hariomhearts** [comment]
tu gandu kamine

**Comment by Raizel-thebloodstorm** [comment]
aur item kaisi hai

**Pull request merged**
